//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestSuppliesMap
    {
        public int requestSupplyMapId { get; set; }
        public Nullable<int> suppliesRequestId { get; set; }
        public Nullable<int> supplyId { get; set; }
    
        public virtual SupplyRequest SupplyRequest { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
